/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EMS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        AttendanceGridView();
        MonthlyAttendanceGridView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(31, 31, 31));

        jPanel2.setBackground(new java.awt.Color(28, 28, 28));

        jPanel3.setBackground(new java.awt.Color(0, 174, 219));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(232, 17, 35));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "EMPID", "Name", "Attendance", "Arriving", "Leaving", "ShortL", "Hours", "OT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Reset Month");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Collect Today");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 174, 219));
        jLabel1.setText("Attendance");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMS/Back_24px.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EMPID", "Name", "Present Days", "Absent Days", "OT", "ShortL"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to collect ?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
        
         //Attendance table variables
            int attno;
            String EMPID = null;
            int Mark=1;
            int attShortL = 0;
            int attOT = 0;
        
          //MonthlyAtt table variables
            int present = 0;
            int absent = 0;
            int OT = 0;
            int ShortL = 0;

            //Extra
            int ExPresent = 0;
            int ExAbsent =0;


            //Incremted Variables
            int Inpresent = 0;
            int Inabsent = 0;
            int InOT = 0;
            int InShortLeaves = 0;
        
        
        
        Connection conn = DBConn.connect();
        
        
        
            for (attno = 1; attno < 100; attno++)
            {
            //Attendance
                try{
                 String attquery = "SELECT * FROM attendance where AttNO = '"+attno+"' ";
                 Statement attst = conn.createStatement();
                 ResultSet attrs = attst.executeQuery(attquery);
                 
                        while (attrs.next())
                        {
                          EMPID = attrs.getString("EMPID");
                          Mark = attrs.getInt("Mark");
                          attShortL = attrs.getInt("ShortL");
                          attOT = attrs.getInt("OT");
                         // JOptionPane.showMessageDialog(null,"Getting Attandance Data "+"   "+EMPID+"   "+Mark+"   "+attShortL+"   "+attOT); 


                        }
                 
                 }catch(SQLException e){
                     JOptionPane.showMessageDialog(null,"Error in Getting Attandance Data "+e); 
                 }
                
                
                
                
                
                //Monthly
                 try{
                 String queryM = "SELECT * FROM monthlyatt where EMPID = '"+EMPID+"' ";
                 Statement stM = conn.createStatement();
                 ResultSet rsM = stM.executeQuery(queryM);
                 
                        while (rsM.next())
                        {
                          present = rsM.getInt("PresentDays");
                          absent = rsM.getInt("AbsentDays");
                          OT = rsM.getInt("OT");
                          ShortL = rsM.getInt("ShortLeaves");

                     //JOptionPane.showMessageDialog(null,"Getting MonthAttandance Data "+"   "+present+"   "+absent+"   "+OT+"   "+ShortL);
                        }
                 
                 }catch(SQLException e){
                     JOptionPane.showMessageDialog(null,"Error in Getting MonthAttandance Data "+e); 
                 }
                
                  if (Mark == 1)
                    {
                      
                        ExAbsent =  0;
                        ExPresent = 1;

                    }
                  else
                    {
                        ExAbsent =  1;
                        ExPresent = 0;
                 
                    }
                 
                              
                    Inpresent = present + ExPresent;
                    Inabsent = absent + ExAbsent;
                    InOT = OT + attOT;
                    InShortLeaves = ShortL + attShortL;
                
                
               // JOptionPane.showMessageDialog(null,"Getting updateing Data "+"   "+Inpresent+"   "+Inabsent+"   "+InOT+"   "+InShortLeaves);
                
                 try{
                      String attquery = "update monthlyatt set PresentDays = '"+Inpresent+"', AbsentDays = '"+Inabsent+"', OT = '"+InOT+"', ShortLeaves = '"+InShortLeaves+"' where EMPID = ?";
                      PreparedStatement preparedStmt = conn.prepareStatement(attquery);
                      preparedStmt.setString(1, EMPID);
                      preparedStmt.executeUpdate();
                 
                      
                 
                 }catch(SQLException e){
                     JOptionPane.showMessageDialog(null,"Error in Updating "+e); 
                 }
                
               Inpresent=0;
               Inabsent=0;
               InOT=0;
               InShortLeaves =0;
               EMPID = null;
               
               
               
               
               
               
               //Preparing For Next Day
               
                 try{
                      String ResetAttquery = "update attendance set Attended = 'Absent', Arriving = '2020-01-01 00:00:00', Leaving = '2020-01-01 00:00:00', Mark = '0', ShortL = '0', Hours = '0', OT = '0' where AttNO = ?";
                      PreparedStatement preparedStmtR = conn.prepareStatement(ResetAttquery);
                      preparedStmtR.setInt(1, attno);
                      preparedStmtR.executeUpdate();
                 
                      
                 
                 }catch(SQLException e){
                     JOptionPane.showMessageDialog(null,"Error in Preparing Next day "+e); 
                 }
               
                     
                
            }
        
        JOptionPane.showMessageDialog(null,"Day Collected Successfuly....!!!"); 
        AttendanceGridView();
        MonthlyAttendanceGridView();
        
        
  
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         Employee Employee = new Employee();
   Employee.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to reset?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            //Month Resetting
            
            
                    Connection conn = DBConn.connect();
        
                    int attno;
        
                 for (attno = 1; attno < 100; attno++){
            
            
            
                 try{
                      String attquery = "update monthlyatt set PresentDays = '0', AbsentDays = '0', OT = '0', ShortLeaves = '0' where Count = ?";
                      PreparedStatement preparedStmt = conn.prepareStatement(attquery);
                      preparedStmt.setInt(1, attno);
                      preparedStmt.executeUpdate();
                 
                      
                 
                 }catch(SQLException e){
                     JOptionPane.showMessageDialog(null,"Error in Updating "+e); 
                 }
                 
                 
                 }
            
                    JOptionPane.showMessageDialog(null,"Month Reseted Successfuly....!!!"); 
                        AttendanceGridView();
                        MonthlyAttendanceGridView();
            
            
            
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
        public final void AttendanceGridView(){
        
        try{
            
            Connection conn = DBConn.connect();
            PreparedStatement ps = conn.prepareStatement("Select * from attendance");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
            tm.setRowCount(0);
            
            while(rs.next()){
                
                Object o[] = {rs.getInt("EMPID"),rs.getString("Name"),rs.getString("Attended"),rs.getString("Arriving"),
                    rs.getString("Leaving"),rs.getString("ShortL"),rs.getString("Hours"),rs.getString("OT")};
                tm.addRow(o);
                
                
                
            }
            
            
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null,"Error in Attendance Grid View..... "+e);
        }
        
        
        
    }
        
        
        
        
        
        
            
        public final void MonthlyAttendanceGridView(){
        
        try{
            
            Connection conn = DBConn.connect();
            PreparedStatement ps = conn.prepareStatement("Select * from monthlyatt");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)jTable2.getModel();
            tm.setRowCount(0);
            
            while(rs.next()){
                
                Object o[] = {rs.getInt("EMPID"),rs.getString("FName"),rs.getString("PresentDays"),rs.getString("AbsentDays"),
                    rs.getString("OT"),rs.getString("ShortLeaves")};
                tm.addRow(o);
                
                
                
            }
            
            
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null,"Error in Monthly Grid View..... "+e);
        }
        
        
        
    }
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void Close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
